// Produits alimentaires marocains
export const MOROCCAN_PRODUCTS = [
  {
    id: '1',
    name: 'Huile d\'Argan Bio',
    category: 'Huiles',
    price: 180,
    unit: 'L',
    stock: 45,
    supplierId: 's1',
    supplierName: 'Coopérative Tissaliwine',
    origin: 'Essaouira',
    description: 'Huile d\'argan 100% pure, pressée à froid',
    image: 'https://images.unsplash.com/photo-1615313041806-57b68b8a8f6c',
    minStock: 20,
    maxStock: 100,
  },
  {
    id: '2',
    name: 'Dattes Medjoul Premium',
    category: 'Fruits Secs',
    price: 95,
    unit: 'kg',
    stock: 120,
    supplierId: 's2',
    supplierName: 'Palmeraie Zagora',
    origin: 'Zagora',
    description: 'Dattes Medjoul de première qualité',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5',
    minStock: 30,
    maxStock: 200,
  },
  {
    id: '3',
    name: 'Sucre Jaouda',
    category: 'Sucres',
    price: 12,
    unit: 'kg',
    stock: 300,
    supplierId: 's3',
    supplierName: 'Suprimer Jaouda',
    origin: 'Casablanca',
    description: 'Sucre semoule de qualité supérieure',
    image: 'https://cdn.leroidessucres.fr/2630-large_default/sucre-semoule-jaouda.jpg',
    minStock: 50,
    maxStock: 500,
  },
  {
    id: '4',
    name: 'Safran de Taliouine',
    category: 'Épices',
    price: 850,
    unit: '10g',
    stock: 28,
    supplierId: 's4',
    supplierName: 'Coopérative Taliouine',
    origin: 'Taliouine',
    description: 'Safran pistils, IGP Taliouine',
    image: 'https://images.unsplash.com/photo-1596049158589-22a0c2f5df5c',
    minStock: 10,
    maxStock: 50,
  },
  {
    id: '5',
    name: 'Amandes de Taroudant',
    category: 'Noix',
    price: 140,
    unit: 'kg',
    stock: 75,
    supplierId: 's5',
    supplierName: 'Ferme Taroudant',
    origin: 'Taroudant',
    description: 'Amandes fraîches, variété Marcona',
    image: 'https://images.unsplash.com/photo-1592317990872-1fd14c9f6a93',
    minStock: 20,
    maxStock: 150,
  },
  {
    id: '6',
    name: 'Miel d\'Eucalyptus',
    category: 'Miels',
    price: 120,
    unit: '500g',
    stock: 60,
    supplierId: 's6',
    supplierName: 'Apiculteur Ifrane',
    origin: 'Ifrane',
    description: 'Miel pur, récolte artisanale',
    image: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924',
    minStock: 15,
    maxStock: 100,
  },
  {
    id: '7',
    name: 'Olives de Meknès',
    category: 'Conserves',
    price: 45,
    unit: 'kg',
    stock: 200,
    supplierId: 's7',
    supplierName: 'Moulin Meknès',
    origin: 'Meknès',
    description: 'Olives vertes marinées aux herbes',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c',
    minStock: 40,
    maxStock: 300,
  },
  {
    id: '8',
    name: 'Couscous Moyen',
    category: 'Céréales',
    price: 35,
    unit: 'kg',
    stock: 150,
    supplierId: 's8',
    supplierName: 'Minoterie Fès',
    origin: 'Fès',
    description: 'Couscous de blé dur, grain moyen',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187',
    minStock: 30,
    maxStock: 200,
  },
  {
    id: '9',
    name: 'Thé Vert Gunpowder',
    category: 'Thés',
    price: 85,
    unit: '500g',
    stock: 90,
    supplierId: 's9',
    supplierName: 'Théière Chefchaouen',
    origin: 'Chefchaouen',
    description: 'Thé vert de qualité supérieure',
    image: 'https://images.unsplash.com/photo-1560343090-f0409e92791a',
    minStock: 20,
    maxStock: 150,
  },
];

// Fournisseurs
export const SUPPLIERS = [
  {
    id: 's1',
    name: 'Coopérative Tissaliwine',
    type: 'Huiles d\'argan',
    location: 'Essaouira',
    phone: '+212 5 24 78 56 12',
    email: 'contact@tissaliwine.ma',
    rating: 4.8,
    products: ['Huile d\'Argan', 'Cosmétiques'],
  },
  {
    id: 's2',
    name: 'Palmeraie Zagora',
    type: 'Dattes et fruits secs',
    location: 'Zagora',
    phone: '+212 5 24 88 45 67',
    email: 'contact@palmeraie-zagora.ma',
    rating: 4.7,
    products: ['Dattes Medjoul', 'Dattes Deglet Nour'],
  },
  {
    id: 's3',
    name: 'Suprimer Jaouda',
    type: 'Sucre et produits alimentaires',
    location: 'Casablanca',
    phone: '+212 5 22 34 56 78',
    email: 'contact@jaouda.ma',
    rating: 4.9,
    products: ['Sucre Jaouda', 'Farine', 'Thé'],
  },
];

// Commandes simulées
export const ORDERS = [
  {
    id: 'CMD001',
    date: '2026-02-10',
    clientId: 'c1',
    clientName: 'SuperMart Nador',
    supplierId: 's3',
    supplierName: 'Suprimer Jaouda',
    items: [
      { productId: '3', name: 'Sucre Jaouda', quantity: 50, price: 12, unit: 'kg' },
    ],
    total: 600,
    status: ORDER_STATUS.PENDING,
    shippingAddress: 'Nador, Maroc',
  },
  {
    id: 'CMD002',
    date: '2026-02-09',
    clientId: 'c1',
    clientName: 'SuperMart Nador',
    supplierId: 's1',
    supplierName: 'Coopérative Tissaliwine',
    items: [
      { productId: '1', name: 'Huile d\'Argan Bio', quantity: 10, price: 180, unit: 'L' },
    ],
    total: 1800,
    status: ORDER_STATUS.VALIDATED,
    shippingAddress: 'Nador, Maroc',
  },
  {
    id: 'CMD003',
    date: '2026-02-08',
    clientId: 'c1',
    clientName: 'SuperMart Nador',
    supplierId: 's2',
    supplierName: 'Palmeraie Zagora',
    items: [
      { productId: '2', name: 'Dattes Medjoul', quantity: 20, price: 95, unit: 'kg' },
    ],
    total: 1900,
    status: ORDER_STATUS.SHIPPED,
    shippingAddress: 'Nador, Maroc',
  },
];